"""add skills column

Revision ID: b201e15ba498
Revises: fbb51a5db6b2
Create Date: 2026-07-19 13:46:55.926716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b201e15ba498'
down_revision: Union[str, Sequence[str], None] = 'fbb51a5db6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('skills', sa.String(length=225), nullable=True))
    op.alter_column('job_postings', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('job_postings', 'company',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('job_postings', 'location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.alter_column('job_postings', 'location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('job_postings', 'company',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('job_postings', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('job_postings', 'skills')
    # ### end Alembic commands ###
